In [ ]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("/content/kidney_disease.csv")
data.head(10)

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
5,5,60.0,90.0,1.015,3.0,0.0,NaN,NaN,notpresent,notpresent,...,39,7800,4.4,yes,yes,no,good,yes,no,ckd
6,6,68.0,70.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,...,36,NaN,NaN,no,no,no,good,no,no,ckd
7,7,24.0,NaN,1.015,2.0,4.0,normal,abnormal,notpresent,notpresent,...,44,6900,5,no,yes,no,good,yes,no,ckd
8,8,52.0,100.0,1.015,3.0,0.0,normal,abnormal,present,notpresent,...,33,9600,4.0,yes,yes,no,good,no,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,...,29,12100,3.7,yes,yes,no,poor,no,yes,ckd

In [ ]:
data.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

dropping id column and removing duplicate values as well from every attribute

In [ ]:
for i in data.drop("id",axis=1).columns:
    print('unique values in "{}":\n'.format(i),data[i].unique())

unique values in "age":
 [48.  7. 62. 51. 60. 68. 24. 52. 53. 50. 63. 40. 47. 61. 21. 42. 75. 69.
 nan 73. 70. 65. 76. 72. 82. 46. 45. 35. 54. 11. 59. 67. 15. 55. 44. 26.
 64. 56.  5. 74. 38. 58. 71. 34. 17. 12. 43. 41. 57.  8. 39. 66. 81. 14.
 27. 83. 30.  4.  3.  6. 32. 80. 49. 90. 78. 19.  2. 33. 36. 37. 23. 25.
 20. 29. 28. 22. 79.]
unique values in "bp":
 [ 80.  50.  70.  90.  nan 100.  60. 110. 140. 180. 120.]
unique values in "sg":
 [1.02  1.01  1.005 1.015   nan 1.025]
unique values in "al":
 [ 1.  4.  2.  3.  0. nan  5.]
unique values in "su":
 [ 0.  3.  4.  1. nan  2.  5.]
unique values in "rbc":
 [nan 'normal' 'abnormal']
unique values in "pc":
 ['normal' 'abnormal' nan]
unique values in "pcc":
 ['notpresent' 'present' nan]
unique values in "ba":
 ['notpresent' 'present' nan]
unique values in "bgr":
 [121.  nan 423. 117. 106.  74. 100. 410. 138.  70. 490. 380. 208.  98.
 157.  76.  99. 114. 263. 173.  95. 108. 156. 264. 123.  93. 107. 159.
 140. 171. 270.  92. 137. 204.  79. 207. 124. 144.  91. 162. 246. 253.
 141. 182.  86. 150. 146. 425. 112. 250. 360. 163. 129. 133. 102. 158.
 165. 132. 104. 127. 415. 169. 251. 109. 280. 210. 219. 295.  94. 172.
 101. 298. 153.  88. 226. 143. 115.  89. 297. 233. 294. 323. 125.  90.
 308. 118. 224. 128. 122. 214. 213. 268. 256.  84. 105. 288. 139.  78.
 273. 242. 424. 303. 148. 160. 192. 307. 220. 447. 309.  22. 111. 261.
 215. 234. 131. 352.  80. 239. 110. 130. 184. 252. 113. 230. 341. 255.
 103. 238. 248. 120. 241. 269. 201. 203. 463. 176.  82. 119.  97.  96.
  81. 116. 134.  85.  83.  87.  75.]
unique values in "bu":
 [ 36.   18.   53.   56.   26.   25.   54.   31.   60.  107.   55.   72.
  86.   90.  162.   46.   87.   27.  148.  180.  163.    nan  50.   75.
  45.   28.  155.   33.   39.  153.   29.   65.  103.   70.   80.   20.
 202.   77.   89.   24.   17.   32.  114.   66.   38.  164.  142.   96.
 391.   15.  111.   73.   19.   92.   35.   16.  139.   48.   85.   98.
 186.   37.   47.   52.   82.   51.  106.   22.  217.   88.  118.   50.1
  71.   34.   40.   21.  219.   30.  125.  166.   49.  208.  176.   68.
 145.  165.  322.   23.  235.  132.   76.   42.   44.   41.  113.    1.5
 146.   58.  133.  137.   67.  115.  223.   98.6 158.   94.   74.  150.
  61.   57.   95.  191.   93.  241.   64.   79.  215.  309.   10. ]
unique values in "sc":
 [ 1.2   0.8   1.8   3.8   1.4   1.1  24.    1.9   7.2   4.    2.7   2.1
  4.6   4.1   9.6   2.2   5.2   1.3   1.6   3.9  76.    7.7    nan  2.4
  7.3   1.5   2.5   2.    3.4   0.7   1.   10.8   6.3   5.9   0.9   3.
  3.25  9.7   6.4   3.2  32.    0.6   6.1   3.3   6.7   8.5   2.8  15.
  2.9   1.7   3.6   5.6   6.5   4.4  10.2  11.5   0.5  12.2   5.3   9.2
 13.8  16.9   6.    7.1  18.    2.3  13.   48.1  14.2  16.4   2.6   7.5
  4.3  18.1  11.8   9.3   6.8  13.5  12.8  11.9  12.   13.4  15.2  13.3
  0.4 ]
unique values in "sod":
 [  nan 111.  142.  104.  114.  131.  138.  135.  130.  141.  139.    4.5
 136.  129.  140.  132.  133.  134.  125.  163.  137.  128.  143.  127.
 146.  126.  122.  147.  124.  115.  145.  113.  120.  150.  144. ]
unique values in "pot":
 [ nan  2.5  3.2  4.   3.7  4.2  5.8  3.4  6.4  4.9  4.1  4.3  5.2  3.8
  4.6  3.9  4.7  5.9  4.8  4.4  6.6 39.   5.5  5.   3.5  3.6  7.6  2.9
  4.5  5.7  5.4  5.3 47.   6.3  5.1  5.6  3.   2.8  2.7  6.5  3.3]
unique values in "hemo":
 [15.4 11.3  9.6 11.2 11.6 12.2 12.4 10.8  9.5  9.4  9.7  9.8  5.6  7.6
 12.6 12.1 12.7 10.3  7.7 10.9  nan 11.1  9.9 12.5 12.9 10.1 12.  13.
  7.9  9.3 15.  10.   8.6 13.6 10.2 10.5  6.6 11.   7.5 15.6 15.2  4.8
  9.1  8.1 11.9 13.5  8.3  7.1 16.1 10.4  9.2  6.2 13.9 14.1  6.  11.8
 11.7 11.4 14.   8.2 13.2  6.1  8.  12.3  8.4 14.3  9.   8.7 10.6 13.1
 10.7  5.5  5.8  6.8  8.8  8.5 13.8 11.5  7.3 13.7 12.8 13.4  6.3  3.1
 17.  15.9 14.5 15.5 16.2 14.4 14.2 16.3 14.8 16.5 15.7 13.3 14.6 16.4
 16.9 16.  14.7 16.6 14.9 16.7 16.8 15.8 15.1 17.1 17.2 15.3 17.3 17.4
 17.7 17.8 17.5 17.6]
unique values in "pcv":
 ['44' '38' '31' '32' '35' '39' '36' '33' '29' '28' nan '16' '24' '37' '30'
 '34' '40' '45' '27' '48' '\t?' '52' '14' '22' '18' '42' '17' '46' '23'
 '19' '25' '41' '26' '15' '21' '43' '20' '\t43' '47' '9' '49' '50' '53'
 '51' '54']
unique values in "wc":
 ['7800' '6000' '7500' '6700' '7300' nan '6900' '9600' '12100' '4500'
 '12200' '11000' '3800' '11400' '5300' '9200' '6200' '8300' '8400' '10300'
 '9800' '9100' '7900' '6400' '8600' '18900' '21600' '4300' '8500' '11300'
 '7200' '7700' '14600' '6300' '\t6200' '7100' '11800' '9400' '5500' '5800'
 '13200' '12500' '5600' '7000' '11900' '10400' '10700' '12700' '6800'
 '6500' '13600' '10200' '9000' '14900' '8200' '15200' '5000' '16300'
 '12400' '\t8400' '10500' '4200' '4700' '10900' '8100' '9500' '2200'
 '12800' '11200' '19100' '\t?' '12300' '16700' '2600' '26400' '8800'
 '7400' '4900' '8000' '12000' '15700' '4100' '5700' '11500' '5400' '10800'
 '9900' '5200' '5900' '9300' '9700' '5100' '6600']
unique values in "rc":
 ['5.2' nan '3.9' '4.6' '4.4' '5' '4.0' '3.7' '3.8' '3.4' '2.6' '2.8' '4.3'
 '3.2' '3.6' '4' '4.1' '4.9' '2.5' '4.2' '4.5' '3.1' '4.7' '3.5' '6.0'
 '5.0' '2.1' '5.6' '2.3' '2.9' '2.7' '8.0' '3.3' '3.0' '3' '2.4' '4.8'
 '\t?' '5.4' '6.1' '6.2' '6.3' '5.1' '5.8' '5.5' '5.3' '6.4' '5.7' '5.9'
 '6.5']
unique values in "htn":
 ['yes' 'no' nan]
unique values in "dm":
 ['yes' 'no' ' yes' '\tno' '\tyes' nan]
unique values in "cad":
 ['no' 'yes' '\tno' nan]
unique values in "appet":
 ['good' 'poor' nan]
unique values in "pe":
 ['no' 'yes' nan]
unique values in "ane":
 ['no' 'yes' nan]
unique values in "classification":
 ['ckd' 'ckd\t' 'notckd']

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [ ]:
data.describe()

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
count,400.000000,391.000000,388.000000,353.000000,354.000000,351.000000,356.000000,381.000000,383.000000,313.000000,312.000000,348.000000
mean,199.500000,51.483376,76.469072,1.017408,1.016949,0.450142,148.036517,57.425722,3.072454,137.528754,4.627244,12.526437
std,115.614301,17.169714,13.683637,0.005717,1.352679,1.099191,79.281714,50.503006,5.741126,10.408752,3.193904,2.912587
min,0.000000,2.000000,50.000000,1.005000,0.000000,0.000000,22.000000,1.500000,0.400000,4.500000,2.500000,3.100000
25%,99.750000,42.000000,70.000000,1.010000,0.000000,0.000000,99.000000,27.000000,0.900000,135.000000,3.800000,10.300000
50%,199.500000,55.000000,80.000000,1.020000,0.000000,0.000000,121.000000,42.000000,1.300000,138.000000,4.400000,12.650000
75%,299.250000,64.500000,80.000000,1.020000,2.000000,0.000000,163.000000,66.000000,2.800000,142.000000,4.900000,15.000000
max,399.000000,90.000000,180.000000,1.025000,5.000000,5.000000,490.000000,391.000000,76.000000,163.000000,47.000000,17.800000

#Data Cleaning

In [ ]:
for i in range(data.shape[0]):
    if data.iloc[i,25]=='ckd\t':
        data.iloc[i,25]='ckd'
    if data.iloc[i,20] in [' yes','\tyes']:
        data.iloc[i,20]='yes'
    if data.iloc[i,20]=='\tno':
        data.iloc[i,20]='no'
    if data.iloc[i,21]=='\tno':
        data.iloc[i,21]='no'
    if data.iloc[i,16]=='\t?':
        data.iloc[i,16]=np.nan
    if data.iloc[i,16]=='\t43':
        data.iloc[i,16]='43'
    if data.iloc[i,17]=='\t?':
        data.iloc[i,17]=np.nan
    if data.iloc[i,17]=='\t6200':
        data.iloc[i,17]= '6200'
    if data.iloc[i,17]=='\t8400':
        data.iloc[i,17]= '6200'
    if data.iloc[i,18]=='\t?':
        data.iloc[i,18]=np.nan
    if data.iloc[i,25]=='ckd':
        data.iloc[i,25]='yes'
    if data.iloc[i,25]=='notckd':
        data.iloc[i,25]='no'

In [ ]:
data.shape

(400, 26)

In [ ]:
data = pd.get_dummies(data)
data

,id,age,bp,sg,al,su,bgr,bu,sc,sod,...,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes,classification_no,classification_yes
0,0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,NaN,...,1,0,1,0,1,0,1,0,0,1
1,1,7.0,50.0,1.020,4.0,0.0,NaN,18.0,0.8,NaN,...,1,0,1,0,1,0,1,0,0,1
2,2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,NaN,...,1,0,0,1,1,0,0,1,0,1
3,3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,...,1,0,0,1,0,1,0,1,0,1
4,4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,NaN,...,1,0,1,0,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,140.0,49.0,0.5,150.0,...,1,0,1,0,1,0,1,0,1,0
396,396,42.0,70.0,1.025,0.0,0.0,75.0,31.0,1.2,141.0,...,1,0,1,0,1,0,1,0,1,0
397,397,12.0,80.0,1.020,0.0,0.0,100.0,26.0,0.6,137.0,...,1,0,1,0,1,0,1,0,1,0
398,398,17.0,60.0,1.025,0.0,0.0,114.0,50.0,1.0,135.0,...,1,0,1,0,1,0,1,0,1,0
399,399,58.0,80.0,1.025,0.0,0.0,131.0,18.0,1.1,141.0,...,1,0,1,0,1,0,1,0,1,0

In [ ]:
data.shape

(400, 213)

In [ ]:
#separate features and labels
labels = np.array(data['classification_yes'])
features = data.drop(['id', 'classification_no', 'classification_yes'], axis=1)  # Exclude unnecessary columns
features = np.array(features)

In [ ]:
features.shape

(400, 210)

In [ ]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets with 80% for training and 20% for testing
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size=0.20, random_state=42)

In [ ]:
import numpy as np

# Find rows without NaN values in any column and keep them
mask = ~np.isnan(train_features).any(axis=1)
train_features = train_features[mask]
train_labels = train_labels[mask]

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=1000, random_state=42)
rf.fit(train_features, train_labels)

RandomForestRegressor(n_estimators=1000, random_state=42)

In [ ]:
import numpy as np

# Check for NaN or Infinity values in test_features
print(np.isnan(test_features).any())
print(np.isfinite(test_features).all())

True
False

In [ ]:
from sklearn.impute import SimpleImputer

# Create a SimpleImputer to fill NaN values with the mean of the column
imputer = SimpleImputer(strategy='mean')

# Fit and transform the test_features array using the imputer
test_features = imputer.fit_transform(test_features)

In [ ]:
prediction = rf.predict(test_features)

In [ ]:
prediction

array([0.998, 0.09 , 1.   , 1.   , 1.   , 1.   , 0.   , 1.   , 0.011,
       1.   , 1.   , 0.   , 1.   , 0.996, 1.   , 0.935, 0.   , 0.   ,
       1.   , 0.   , 1.   , 1.   , 0.   , 0.   , 0.037, 0.   , 1.   ,
       1.   , 0.   , 1.   , 0.   , 0.999, 0.   , 1.   , 1.   , 0.699,
       1.   , 0.001, 1.   , 1.   , 0.003, 1.   , 1.   , 0.997, 1.   ,
       0.   , 1.   , 0.999, 0.999, 0.966, 0.697, 0.   , 0.   , 0.157,
       0.   , 0.983, 0.874, 1.   , 1.   , 0.927, 1.   , 0.   , 0.   ,
       1.   , 1.   , 1.   , 0.   , 0.089, 0.   , 1.   , 0.   , 0.689,
       0.729, 1.   , 0.   , 1.   , 1.   , 0.   , 1.   , 0.   ])

In [ ]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(test_labels, prediction)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 0.025420612500000002

In [ ]:
errors = abs(prediction-test_labels)

In [ ]:
errors

array([0.002, 0.09 , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.011,
       0.   , 0.   , 0.   , 0.   , 0.004, 0.   , 0.065, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.963, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.001, 0.   , 0.   , 0.   , 0.301,
       0.   , 0.001, 0.   , 0.   , 0.003, 0.   , 0.   , 0.003, 0.   ,
       0.   , 0.   , 0.001, 0.001, 0.034, 0.303, 0.   , 0.   , 0.843,
       0.   , 0.017, 0.126, 0.   , 0.   , 0.073, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.089, 0.   , 0.   , 0.   , 0.311,
       0.271, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [ ]:
mae = (errors/test_labels)

<ipython-input-23-dee2374b5fb7>:1: RuntimeWarning: divide by zero encountered in divide
  mae = (errors/test_labels)
<ipython-input-23-dee2374b5fb7>:1: RuntimeWarning: invalid value encountered in divide
  mae = (errors/test_labels)

In [ ]:
mae

array([0.002,   inf, 0.   , 0.   , 0.   , 0.   ,   nan, 0.   ,   inf,
       0.   , 0.   ,   nan, 0.   , 0.004, 0.   , 0.065,   nan,   nan,
       0.   ,   nan, 0.   , 0.   ,   nan,   nan, 0.963,   nan, 0.   ,
       0.   ,   nan, 0.   ,   nan, 0.001,   nan, 0.   , 0.   , 0.301,
       0.   ,   inf, 0.   , 0.   ,   inf, 0.   , 0.   , 0.003, 0.   ,
         nan, 0.   , 0.001, 0.001, 0.034, 0.303,   nan,   nan, 0.843,
         nan, 0.017, 0.126, 0.   , 0.   , 0.073, 0.   ,   nan,   nan,
       0.   , 0.   , 0.   ,   nan,   inf,   nan, 0.   ,   nan, 0.311,
       0.271, 0.   ,   nan, 0.   , 0.   ,   nan, 0.   ,   nan])

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

threshold = 0.5
binary_predictions = (prediction > threshold).astype(int)

# Calculate accuracy
accuracy = accuracy_score(test_labels, binary_predictions)

# Calculate precision, recall, and F1-score
precision = precision_score(test_labels, binary_predictions)
recall = recall_score(test_labels, binary_predictions)
f1 = f1_score(test_labels, binary_predictions)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")

Accuracy: 0.975
Precision: 1.0
Recall: 0.9615384615384616
F1-score: 0.9803921568627451

In [ ]:
accuracy

0.975

In [ ]:
from sklearn.tree import export_graphviz
import pydot

tree = rf.estimators_[10]

export_graphviz(tree, out_file='tree.dot')
(graph, ) = pydot.graph_from_dot_file('tree.dot')
graph.write_png('tree.png')